### ISSUE TITLE
Wrong e-mail details when querying a record.

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/asian-hornet-watch-app#50]
When querying a record via the Verification grid, the e-mail displayed under the e-mail tab is "apps@ceh.ac.uk".  This field needs to show the e-mail address provided by the user so we can get in contact if needed.

**Comment by kazlauskis** [comment]
Thanks, I think this should be done on the server side. The anonymous user email is attached as an attribute. @johnvanbreda

**Comment by MNSmith** [comment]
Any progress with a fix for this?  When using the e-mail facility on a record I am not sure if the query / follow up e-mail is actually going to the recorder.
