### ISSUE TITLE
Record not displaying on map?

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/asian-hornet-watch-app#51]
Normally, with records in iRecord, clicking on the record in the verification grid caused the map display to zoom in and display a red square on the map.  This is not happening with records arriving via the Asian Hornet app.  Possibly related to the geo-location issue raised earlier?  We do need this facility.

**Comment by kazlauskis** [comment]
Yes, this probably relates to #49. If so then I think this should also be done on the server side. @johnvanbreda

**Comment by johnvanbreda** [comment]
Fixed. The mapping of low resolution layers (e.g. 10km when zoomed out) was skipping sensitive records if the blur was higher than the current layer precision, even if you had rights to the full precision. Now it shows the record at the appropriate precision (i.e. full precision).

**Comment by DavidRoy** [comment]
@kazlauskis this issue can be closed
