### ISSUE TITLE
App duplicating records?

### ISSUE THREAD

**Issue by MNSmith** [NERC-CEH/asian-hornet-watch-app#52]
I have been wondering for a while if the App is somehow duplicating at least some of the incoming records.  For a number of records, but not all, I am seeing one record where the Recorder field contains the name of a recorder, and then a second record with identical details where the Recorder field contains "Asian Hornet Watch, ?".  Is this down to the user pressing the submit key more than once or a glitch in the App?  See this pair of records:

![image](https://user-images.githubusercontent.com/18451743/26890068-3a724432-4ba8-11e7-9421-354515782d91.png)

![image](https://user-images.githubusercontent.com/18451743/26890126-68224cf6-4ba8-11e7-976d-82933177813d.png)

**Comment by kazlauskis** [comment]
Hi @MNSmith, it is strange that those two have different GPS coordinates making them two different records. My guess is that the user has recorded one anonymously and then another one using his iRecord account but submitted them at the same time. Did you see more of such records?

**Comment by MNSmith** [comment]
I don't think this is the case, I think the App is somehow duplicating the records.  The records have identical calculated OS Grid References, the differences in the Lat/Long are minimal and can be ascribed to the phone GPS system seeing the point "move" slightly as is normal.  Also, look at the time of record submission, they were submitted 3 seconds apart.

Another pair of records today - see 5116597 and 5116583.  Same situation, one from the recorder and one from "Asian Hornet Watch?".  Where is this "Asian Hornet Watch?" name coming from?

**Comment by kazlauskis** [comment]
The 'Asian Hornet Watch?' name is associated with anonymous recording account. It is interesting that those two have different comments attached to them.

**Comment by MNSmith** [comment]
Another pair if records - 5243400 and 5243401 - posting time is the same but the geo-location is very different.  Something odd here.

**Comment by kazlauskis** [comment]
Yup, looks like there might be a bug in the app somewhere. Thanks for reporting this and please update this thread if you find more of those, maybe we could identify some pattern here to narrow down the issue.

**Comment by MNSmith** [comment]
Another pair of records - 5353110 and 5353121

**Comment by MNSmith** [comment]
Two more record pairs:

5444790 and 5444766

5436887 and 5436906

**Comment by MNSmith** [comment]
Two more record pairs.  This time the App seems to be duplicating identical records, both of these pairs of records appear to be identical apart from the fact they were submitted 1 second apart according to the time on the record.

5486836 and 5486837

5483242 and 5483243
