### ISSUE TITLE
Allow anonymous record upload directly to the warehouse

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/asian-hornet-watch-app#57]
An idea how this could be handled:

1. In the Warehouse add an anonymous website checkbox that could be enabled in the website's profile.
2. An app would use a [Client Credentials](https://www.rfc-editor.org/rfc/rfc6749#section-4.4) grant to authenticate itself for anonymous use with a Drupal site. **This generates a signed JWT token similar to the Password grant we currently use. The token wouldn’t have any user-related values like email or first/last names.** Importantly, it would still be signed and have an expiry (*exp*) and issuer (*iss*) fields.
3. Warehouse accepts a sample/occurrence/media POST request with a JWT token. 
   1. Checks that it hasn’t expired yet.
   2. Finds the website url in the *iss* field. 
      1. Checks the website has a public key set
      2. Because the email in the JWT is missing it also checks that the website has anonymous use checkbox enabled.
   3. Processes the request
5. For anonymous records it rejects existing record modifications (PUT) or direct downloading (GET), only uploading (POST).
6. (optional for now) for anonymous tokens it allows public report use only.

**Comment by kazlauskis** [comment]
@johnvanbreda the BRC site migration has broken the current old app so we've got a bit of a rush to push the new update. Do you know when this task could be done?

**Comment by johnvanbreda** [comment]
I will look at this now @kazlauskis

**Comment by kazlauskis** [comment]
thanks

**Comment by kazlauskis** [comment]
Excellent, I can see it now in the warehouse. I will give it a go this afternoon, cheers!
